### ISSUE TITLE
Is it possible to support USB external HDD?

### ISSUE THREAD

**Issue by timmyhbk** [007revad/Synology_SMART_info#7]
Is there any chance that the script will be able to support USB external HDD? I originally used `smartctl -a -d sat /dev/usb1` to check. But it seems to be not working in the new version of DSM.

Thanks!

**Comment by 007revad** [comment]
For the USB drives I previously tried smartctl didn't work. These were: 
- HDDs in a USB dock.
- HDDs in a USB multi-drive enclosure (with hardware RAID).
- USB flash drives (just out of curiosity).

I just checked my script and I already included support for USB drives, I disabled for some reason. Lines 474 to 478 are commented out. I just removed the # in front of those lines and tested with I just an old 2.5 inch Samsung S2 Portable 3 drive and smartctl worked. I also tried connecting the cable from the USB drive to an unpowered USB hub and the drive didn't even power up.

The only issue is it shows as the same Drive number of the previous drive, instead of showing as USB 1. That should an easy fix.

![image](https://github.com/user-attachments/assets/1a89851b-e0c4-4f4f-a293-c64691b4fca2)

I also need to figure how to avoid USB flash drives as they just cause 6 lines of error messages.

![image](https://github.com/user-attachments/assets/6c0ffffa-f0f3-4f6d-8295-59639c0a9aa9)

**Comment by timmyhbk** [comment]
I also removed the comments from scripts 474 through 478.

I found that only the external HDD that I am mainly using (Seagate Expansion HDD) are not displayed. A few other external SSDs/HDDs did display correctly.

It seems to be a problem with my device, thank you.

![2024-07-21 184124](https://github.com/user-attachments/assets/8779370d-7316-4b02-b9ad-0ae024264c8d)
